### PR TITLE
able to specify the path of the dump image.

### PR DESCRIPTION
**Pull request by ta2gch**
This pull request enable following operations.
- `ros -m <dump-nanme>` 
- `ros -m /path/to/<dump-image> `

### CODE REVIEW

**Comment by snmsts** [comment]
I don't understand why do you need this?

**Comment by ta2gch** [comment]
Because I want to treat the core image in the presence of portability.

Why do you want to limit the location of the core image?

**Comment by snmsts** [comment]
Because dump file is so tricky. There is no compatibility even with same lisp implementation.If you want to manage dump file correctly you should keep track the file was made by which implementation ,which version,which compiled option applied to the lisp altogether.That is what I want to manage by Roswell. I don't want give the confusion back to user again.

I would appreciate if you fix 'ros list dump' problem.

**Comment by ta2gch** [comment]
I see. Thank you for teaching. 

I will try that problem.

**Pull request closed without merging**
