### PR TITLE
Test 'ros install sbcl' on Travis CI (DO NOT MERGE YET)

### PR DESCRIPTION
**Pull request by fukamachi**
When I added `ros install sbcl` to .travis.yml, it raises an error at `sh install.sh` on Travis CI.

https://travis-ci.org/fukamachi/roswell/jobs/46989284#L324

As I never seen the error even on Linux machines, I thought it is an error raised only on Travis CI. However, my coworker encountered the exact same error on EC2 while he was trying to deploy.

Any thoughts?

### CODE REVIEW

**Comment by snmsts** [comment]
I'm not sure but I think this travis case the process are just get signal because it exceed something.
`~/.roswell/impls/log/sbcl-1.2.7/make.log` might be helpful for EC2 case.

**Comment by Rudolph-Miller** [comment]
I have just `~/.roswell/impls/log/sbcl-bin-1.2.7/install.log`.

**Comment by fukamachi** [comment]
Here's what I get from `~/.roswell/impls/log/sbcl-1.2.7/make.log` on Travis CI:

```
/home/travis/build.sh: line 41: --: command not found
```

https://travis-ci.org/fukamachi/roswell/jobs/47008699#L367

**Comment by fukamachi** [comment]
It seems `time` doesn't exist on Travis CI.
After adding `sudo apt-get install time` to `before_script`, it passed successfully.

However, it takes much time (about 7 min) comparing to only running `ros install sbcl-bin`. I don't think it's not necessary to run every time. I think it would be better to close this for now.

Thanks anyway.

**Pull request closed without merging**
