### PR TITLE
add: recipes

### PR DESCRIPTION
**Pull request by Rudolph-Miller**

### CODE REVIEW

**Comment by Rudolph-Miller** [comment]
It works in an engineyard instance, though, it could depend on automake.

**Comment by Rudolph-Miller** [comment]
User should first make sure of automake installed, and install automake might not be the task of this chef file.

**Comment by snmsts** [comment]
Thank you.

**Comment by fukamachi** [comment]
Is using the master branch safe?

**Comment by Rudolph-Miller** [comment]
It could be a problem.

**Comment by Rudolph-Miller** [comment]
I now see there is release br., then I shoild use this.br..

**Comment by snmsts** [comment]
I take it as bit 'pressure' on releasing :).
in any sense, I have no reason for reject merging it to master.

btw, I'd like to change name of the directory that might named including 'chef'.
Do you have any idea on naming?

**Comment by Rudolph-Miller** [comment]
It can be handled by berkshelf if the project has recipes directory.

**Comment by snmsts** [comment]
hm... then it'll be better to keep it.
Thanks.

**Pull request merged**
